yamlApplicationConfig:
   kafka:
     clusters:
       - name: sys1.7
         bootstrapServers: kafka-service:9092
ingress:
  enabled: true
  annotations: {}
  ingressClassName: nginx
  path: "/"
  pathType: "Prefix"  
  host: kafka.yonatan.com