zookeeper:
  enabled: true

replicaCount: 3

auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext

# Specify the broker configuration
kafka:
  configurationOverrides:
    "offsets.topic.replication.factor": 3
    "transaction.state.log.replication.factor": 3
    "transaction.state.log.min.isr": 2

externalAccess:
  enabled: true
  service:
    type: LoadBalancer
