## Kafka listeners configuration
kafka:
  config:
    # Listeners configuration
    listeners: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
    advertised.listeners: INSIDE://kafka-inside:9093,OUTSIDE://kafka-outside:9092
    listener.security.protocol.map: INSIDE:PLAINTEXT,OUTSIDE:SASL_PLAINTEXT
    security.protocol: SASL_PLAINTEXT
    sasl.enabled.mechanisms: PLAIN
    sasl.mechanism.inter.broker.protocol: PLAIN
    inter.broker.listener.name: OUTSIDE

  ## Authentication configuration
  auth:
    enabled: true
    clientProtocol: sasl
    interBrokerProtocol: sasl
    sasl:
      jaas:
        clientUsers:
        - user
        clientPassword:
        - password
        interBrokerUser:
        - user
        interBrokerPassword:
        - password
listeners:
  client:
    containerPort: 9092
    protocol: PLAINTEXT # Use PLAINTEXT instead of SASL_PLAINTEXT
    name: CLIENT
    sslClientAuth: ""
  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: PLAINTEXT # Use PLAINTEXT
    sslClientAuth: ""
  interbroker:
    containerPort: 9094
    protocol: PLAINTEXT # Use PLAINTEXT
    name: INTERNAL
    sslClientAuth: ""
  external:
    containerPort: 9095
    protocol: PLAINTEXT # Use PLAINTEXT
    name: EXTERNAL
    sslClientAuth: ""
  extraListeners: []
  overrideListeners: ""
  advertisedListeners: ""
  securityProtocolMap: ""

## Disable SASL authentication by not using SASL mechanisms
sasl:
  enabledMechanisms: ""
  interBrokerMechanism: ""
  controllerMechanism: ""

## Kafka TLS settings, not needed for PLAINTEXT
tls:
  type: ""
  existingSecret: ""
  autoGenerated: false
  endpointIdentificationAlgorithm: ""
  sslClientAuth: "none"
  zookeeper:
    enabled: false
    verifyHostname: false
    existingSecret: ""
    passwordsSecret: ""
auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
kafka:
  configurationOverrides:
    "offsets.topic.replication.factor": 3
    "transaction.state.log.replication.factor": 3
    "transaction.state.log.min.isr": 2

externalAccess:
  enabled: true
  service:
    type: LoadBalancer

